#!/usr/bin/env bash
#
# Extracts the dashboard's contract ABIs from the Foundry build output.
#
# The web app never hand-maintains an ABI. A hand-copied fragment drifts from the
# contract the moment a function is added, and the failure mode is a dashboard
# that silently reads the wrong slot. Run this after any ABI change, alongside
# ./scripts/generate-bindings.sh which does the same job for the Go tooling.
#
# Usage: ./scripts/generate-web-abis.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/out"
ABI_DIR="$ROOT/web/src/lib/abi"

if ! command -v jq >/dev/null 2>&1; then
    echo "generate-web-abis: jq is required" >&2
    exit 1
fi

# contract source name : exported TypeScript identifier
CONTRACTS=(
    "PolicyEngine:policyEngineAbi"
    "TreasuryRegistry:treasuryRegistryAbi"
    "PaymentController:paymentControllerAbi"
    "AegisInstructionSender:aegisInstructionSenderAbi"
    "ExecutionVerifier:executionVerifierAbi"
)

echo "generate-web-abis: building contracts"
(cd "$ROOT" && forge build >/dev/null)

mkdir -p "$ABI_DIR"

for entry in "${CONTRACTS[@]}"; do
    name="${entry%%:*}"
    ident="${entry##*:}"
    artifact="$OUT_DIR/$name.sol/$name.json"

    if [[ ! -f "$artifact" ]]; then
        echo "generate-web-abis: missing artifact $artifact" >&2
        exit 1
    fi

    target="$ABI_DIR/${ident%Abi}.ts"
    {
        echo "// Generated by scripts/generate-web-abis.sh from out/$name.sol/$name.json."
        echo "// Do not edit by hand — re-run the script after changing the contract."
        echo
        echo "export const $ident = ["
        jq -r '.abi | sort_by(.type, .name // "") | .[] | "  " + (tojson) + ","' "$artifact"
        echo "] as const;"
    } >"$target"

    echo "generate-web-abis: wrote ${target#"$ROOT"/}"
done

index="$ABI_DIR/index.ts"
{
    echo "// Generated by scripts/generate-web-abis.sh."
    echo "// Do not edit by hand — re-run the script after changing the contract."
    echo
    for entry in "${CONTRACTS[@]}"; do
        ident="${entry##*:}"
        echo "export { $ident } from \"./${ident%Abi}\";"
    done
} >"$index"

echo "generate-web-abis: wrote ${index#"$ROOT"/}"
